In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("insurance.csv")

In [3]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(1)

In [7]:
data.drop_duplicates(inplace=True)

In [8]:
data['sex']=data['sex'].map({'male':1,'female':0})

In [9]:
data['smoker'] = data['smoker'].apply(lambda x: 1 if x == 'yes' else 0)

In [10]:
encoded_data=pd.get_dummies(data,columns=['region'],dtype=int)

In [11]:
encoded_data.head(10)

,age,sex,bmi,children,smoker,charges,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,16884.92400,0,0,0,1
1,18,1,33.770,1,0,1725.55230,0,0,1,0
2,28,1,33.000,3,0,4449.46200,0,0,1,0
3,33,1,22.705,0,0,21984.47061,0,1,0,0
4,32,1,28.880,0,0,3866.85520,0,1,0,0
5,31,0,25.740,0,0,3756.62160,0,0,1,0
6,46,0,33.440,1,0,8240.58960,0,0,1,0
7,37,0,27.740,3,0,7281.50560,0,1,0,0
8,37,1,29.830,2,0,6406.41070,1,0,0,0
9,60,0,25.840,0,0,28923.13692,0,1,0,0

In [14]:
X=encoded_data.drop(columns=['charges'])
y=encoded_data['charges']

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [17]:
model.coef_

array([  251.24617223,  -111.90716088,   328.38309611,   522.15536198,
       22874.44640656,   541.85745202,    76.11085558,  -394.24187351,
        -223.72643409])

In [18]:
model.intercept_

np.float64(-12058.63848120459)

In [19]:
y_pred_train=model.predict(X_train)

In [20]:
from sklearn.metrics import r2_score,mean_squared_error
mean_squared_error(y_train,y_pred_train)

35812933.236174285

In [21]:
r2_score(y_train,y_pred_train)

0.7362637207024127

In [22]:
y_pred_test=model.predict(X_test)

In [23]:
mean_squared_error(y_test,y_pred_test)

38940169.92282634

In [25]:
r2_score(y_test,y_pred_test)

0.7724363518631284

In [26]:
user_input = pd.DataFrame({
    'age': [30],                
    'sex': [1],                   # 1 = Male
    'bmi': [25.5],                # Normal BMI
    'children': [2],              # 2 bachay
    'smoker': [1],                # 1 = Smoker (Cigarette peeta hai)
    'region_northeast': [0],
    'region_northwest': [1],      # Northwest region ka rehnay wala
    'region_southeast': [0],
    'region_southwest': [0]
})

In [27]:
model.predict(user_input)

array([27735.47646168])

In [29]:
similar_patients = data[(data['age'] >= 28) & (data['age'] <= 32) & (data['smoker'] == 1)]
display(similar_patients[['age', 'sex', 'bmi', 'smoker', 'charges']])

      age  sex     bmi  smoker      charges
19     30    1  35.300       1  36837.46700
29     31    1  36.300       1  38711.00000
34     28    1  36.400       1  51194.55914
69     28    1  23.980       1  17663.14420
117    29    0  27.940       1  19107.77960
128    32    0  17.765       1  32734.18630
144    30    1  28.690       1  20745.98910
158    30    1  35.530       1  36950.25670
298    31    1  34.390       1  38746.35510
465    30    0  28.380       1  19521.96820
500    29    1  34.400       1  36197.69900
577    31    0  38.095       1  58571.07448
609    30    1  37.800       1  39241.44200
725    30    0  39.050       1  40932.42950
727    29    0  21.755       1  16657.71745
739    29    1  35.500       1  44585.45587
780    30    1  24.400       1  18259.21600
885    32    1  28.930       1  19719.69470
909    32    0  24.600       1  17496.30600
975    29    1  22.895       1  16138.76205
982    31    1  25.900       1  19199.94400
1000   30    1  22.990       1  17361.76610
1078   28    1  31.680       1  34672.14720
1179   31    1  29.810       1  19350.36890
1249   32    1  33.630       1  37607.52770
1306   29    0  21.850       1  16115.30450
1307   32    1  28.120       1  21472.47880
1314   30    0  23.655       1  18765.87545